var count = 0;
      var button1 = document.getElementById("countButton1");
      var button2 = document.getElementById("countButton2");
      var button3 = document.getElementById("countButton3");
      var button4 = document.getElementById("countButton4");
      var button5 = document.getElementById("countButton5");
      var button6 = document.getElementById("countButton6");
      var button7 = document.getElementById("countButton7");
      var button8 = document.getElementById("countButton8");
      var button9 = document.getElementById("countButton9");
      var button10 = document.getElementById("countButton10");
      var button11 = document.getElementById("countButton11");
      var button12 = document.getElementById("countButton12");
      var display = document.getElementById("displayCount");

      button1.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button2.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button3.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button4.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button5.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button6.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button7.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button8.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button9.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button10.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button11.onclick = function(){
        count++;
        display.innerHTML = count;
      }
      button12.onclick = function(){
        count++;
        display.innerHTML = count;
      }